openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://127.0.0.1:5000/
    description: Optional server description, e.g. Main (production) server
paths:
  /hello:
    get:
      summary: Returns a message
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':
          description: A little message
          content:
            application/json:
              schema:
                type: string
    post:
      summary: Returns a nicer message
      description: yep
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              example:
                name: "Jennifer"


      responses:
        201:
          description: Greeted
        400:
          description: Greeted
